### ISSUE TITLE
Relies upon psutil 5.6.6, which currently does not build on Windows

### ISSUE THREAD

**Issue by Mythobeast** [sayanarijit/pidlock#9]
While attempting to install this on a Windows system, it fails because its prerequisite, psutil 5.6.6, does not install properly on Windows. I don't actually need its functionality on Windows, but I do need these libraries to install correctly. Could this get updated, please?

**Comment by vadorvatsal** [comment]
I have same error.

**Comment by sayanarijit** [comment]
Hey @keiranmraine it seems we don't need to pin the requirements down to the minor version digit. I'm updating the pin from 5.6.6 to 5.x.x. I don't think it will cause any issues. Let me know if any concern.

**Comment by sayanarijit** [comment]
Also, @keiranmraine it seems you'll need to update the CircleCI deploy keys in the project setting. I don't have access to them. For now, I'll run the tests locally and merge it.
